### ISSUE TITLE
remove / add options

### ISSUE THREAD

**Issue by ottiauswien** [caseyWebb/selectr#26]
thnx for this really beautiful and useful plugin.
but i need one thing: add and remove option values in runtime. 
it would be helpful, if you would put the LI element an ID, the value for example
then i can add or remove options via jquery (in selectbox and in your box also).

if you won't do that for all in your script, maybe you can be so kind, and send me an modified variant, where the li has an id (the value)
THANKS A LOT!

**Comment by ottiauswien** [comment]
on columt 2698 paste:

.attr("id",e(i).val())

**Comment by caseyWebb** [comment]
If you add an option to the source select element (the element you triggered selectr on), it should update selectr accordingly. To support legacy browsers, you may have to fire a change event on the source as well

**Comment by caseyWebb** [comment]
I think I may have misunderstood you, but if you are trying to change the option value only the above solution should still work. If it doesn't I'd be happy to take a look at it. I'm hesitant to add an `id` however to avoid polluting the DOM and ensuring that the solution would still work with multiple selectr instances on a page.

**Comment by caseyWebb** [comment]
@ottiauswien

**Comment by ottiauswien** [comment]
Thnx, one solution to handle same id's could be to put the Id name from the select as an prefix to all the options. For all Dom handling it would be great to have id's. 
Another helpful thing would be a 'refresh'  method . For example to reorder a updated selectbox. 
Thnx for your good job.

**Comment by caseyWebb** [comment]
A `refresh` method should be unnecessary. As [this fiddle](https://jsfiddle.net/CaseyWebb/d4h1gany/3/) demonstrates, any changes to the source select element should be immediately reflected by selectr. I wrote selectr with the purpose of using with data-binding, so I tried to go to great lengths to ensure everything syncs correctly.

The one exception to this is <IE11 which does not support mutation observers. In that case however, firing a change event, `$('select').trigger('change')`, should cause selectr to update.

If you are having some other issue or trying to do something else, make a fiddle for it and I'd be happy to take a look at it.

And thanks for the kudos, I'm really glad you enjoy it. I enjoyed making it.

**Comment by caseyWebb** [comment]
As far as prefixing the select id, then you run into issues when selectr is used without an id. For instance, we give all of our selects that should be selectrs a class of `selectr` so we can use one jQuery call, `$('.selectr').selectr()` to initialize all of the selectrs on the page. The only option would be to number them, i.e. assign them an id of "selectr-1-opt-1", but this seems far too fragile to me.

**Comment by caseyWebb** [comment]
@ottiauswien

**Comment by ottiauswien** [comment]
thnx for your help.
interesting, i won't get your fiddle work in firefox or chrome. 
the source select is growing, but not selectr. 
in fiddle it works, but when i try the same code local, selectr is not refreshing...

anyway, thank you for this plugin, exactly what i searched for!
best regards from vienna

**Comment by caseyWebb** [comment]
It works in fiddle but not locally? I think we've got something there. I briefly attempted wrapping selectr in a UMD, and after enough issues just rolled back and had some issues getting bower to use the correct package.

How did you install selectr?

**Comment by caseyWebb** [comment]
@ottiauswien Has this been resolved?
